### ISSUE TITLE
No localized files found

### ISSUE THREAD

**Issue by mhintner** [OlivierCC/spfx-40-fantastics#1]
On executing gulp serve I get the following error:
Error - 'collectLocalizedResources' sub task errored after 8.27 ms
 "Error for resource \"testStrings\": No localized files found under the \"lib\" directory matching pattern \"webparts/test/loc/{locale}.js\""
Any ideas on this one?

**Comment by OlivierCC** [comment]
Hi, can you try to update your solution with the last project version and to update your node_module sp-client-custom-fields by executing 'npm u sp-client-custom-fields' ?

**Comment by OlivierCC** [comment]
Hi thx for your report, the problem has been identified and will be fix very soon
