### ISSUE TITLE
News Slider has stopped working

### ISSUE THREAD

**Issue by DS2019** [OlivierCC/spfx-40-fantastics#106]
Today the news slider has stopped working in all instances with this message:

SPLoaderError.loadComponentError]:***Failed to load component "f6adeeb5-6e0c-46e8-a2e3-88b193b6c424" (NewsSlider). Original error: ***Failed to load URL 'https://spfx40fantastics.azureedge.net/spfx40fantastics/newsslider.bundle_67c172fe891a291998576243da5c92e9.js' for resource 'newsSlider.bundle' in component 'f6adeeb5-6e0c-46e8-a2e3-88b193b6c424' (NewsSlider). The access to the file is forbidden.***INNERERROR:***Failed to load URL 'https://spfx40fantastics.azureedge.net/spfx40fantastics/newsslider.bundle_67c172fe891a291998576243da5c92e9.js' for resource 'newsSlider.bundle' in component 'f6adeeb5-6e0c-46e8-a2e3-88b193b6c424' (NewsSlider). The access to the file is forbidden.***CALLSTACK:Error   at t._generateErrorStackForIE (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-09-13.006/sp-classic-page-assembly_en_14927e979d9ad5df6e1d2c6fc4a90fc7.js:3:53807)   at t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-09-13.006/sp-classic-page-assembly_en_14927e979d9ad5df6e1d2c6fc4a90fc7.js:3:53343)   at t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-09-13.006/sp-classic-page-assembly_en_14927e979d9ad5df6e1d2c6fc4a90fc7.js:18:47768)   at e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-09-13.006/sp-classic-page-assembly_en_14927e979d9ad5df6e1d2c6fc4a90fc7.js:18:111543)   at e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-09-13.006/sp-classic-page-assembly_en_14927e979d9ad5df6e1d2c6fc4a90fc7.js:18:107568)   at Anonymous function (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-09-13.006/sp-classic-page-assembly_en_14927e979d9ad5df6e1d2c6fc4a90fc7.js:18:43980)   at Anonymous function (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-09-13.006/sp-classic-page-assembly_en_14927e979d9ad5df6e1d2c6fc4a90fc7.js:1:16160)   at F (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-09-13.006/sp-classic-page-assembly_en_14927e979d9ad5df6e1d2c6fc4a90fc7.js:1:16136)   at C (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-09-13.006/sp-classic-page-assembly_en_14927e979d9ad5df6e1d2c6fc4a90fc7.js:1:15981)   at B (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-09-13.006/sp-classic-page-assembly_en_14927e979d9ad5df6e1d2c6fc4a90fc7.js:1:15569)
--

Anyone else have this?

**Comment by Seanny37** [comment]
We've experiencing a similar issue. When I try to load a .js file directly, I'm seeing a message that the specified account is disabled.

https://spfx40fantastics.azureedge.net/spfx40fantastics/ug-theme-tiles_a2cc65c2042b4ae93a308c336e3d37e2.js

<Error>
<Code>AccountIsDisabled</Code>
<Message>
The specified account is disabled. RequestId:8f75aebb-001e-0083-14ad-73676e000000 Time:2019-09-25T14:25:58.3085634Z
</Message>
</Error>

**Comment by DS2019** [comment]
Tiles stopped working this morning with this:
SPLoaderError.loadComponentError]:
***Failed to load component "ee6ccc68-d0ec-456c-8968-08a705191cf1" (TilesMenu). Original error: ***Failed to load URL 'https://spfx40fantastics.azureedge.net/spfx40fantastics/spfx-40-fantastics-sp-client-custom-fields_strings_en-ca_517cbd7b26367d7a6cbe94ede5a0f7b8.js' for resource 'sp-client-custom-fields/strings' in component 'ee6ccc68-d0ec-456c-8968-08a705191cf1' (TilesMenu). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

***INNERERROR:
***Failed to load URL 'https://spfx40fantastics.azureedge.net/spfx40fantastics/spfx-40-fantastics-sp-client-custom-fields_strings_en-ca_517cbd7b26367d7a6cbe94ede5a0f7b8.js' for resource 'sp-client-custom-fields/strings' in component 'ee6ccc68-d0ec-456c-8968-08a705191cf1' (TilesMenu). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.
***CALLSTACK:
Error
    at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-09-13.006/sp-classic-page-assembly_en_14927e979d9ad5df6e1d2c6fc4a90fc7.js:3:53495)
    at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-09-13.006/sp-classic-page-assembly_en_14927e979d9ad5df6e1d2c6fc4a90fc7.js:18:47776)
    at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-09-13.006/sp-classic-page-assembly_en_14927e979d9ad5df6e1d2c6fc4a90fc7.js:18:111549)
    at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-09-13.006/sp-classic-page-assembly_en_14927e979d9ad5df6e1d2c6fc4a90fc7.js:18:107580)
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-09-13.006/sp-classic-page-assembly_en_14927e979d9ad5df6e1d2c6fc4a90fc7.js:18:43990

**Comment by JyotiAfre** [comment]
all SpFX webparts have stopped working. Any solutions?

**Comment by tomobak** [comment]
We have same issue from this morning.  Please let us know how to fix it.

**Comment by forrman** [comment]
@OlivierCC  we're seeing this HTTPS / cert problem too. Is there a fix?

**Comment by divijc** [comment]
Facing the same issue, looks like the CDN tenant is not working

**Comment by lgroaccess** [comment]
Our firm is experiencing issues with the NewsSlider and NewsCarousel, both giving off the same error message as of yesterday afternoon at 1 pm central time.  Please advise what is occurring and how to resolve it.  :
[SPLoaderError.loadComponentError]:
***Failed to load component "3f378f3d-733d-34b6-8470-17317bb0b275" (NewsCarousel). Original error: ***Failed to load URL 'https://spfx40fantastics.azureedge.net/spfx40fantastics/jquery_510295b52d8a7cc774bf4fb013893d1e.js' for resource 'jquery' in component '3f378f3d-733d-34b6-8470-17317bb0b275' (NewsCarousel). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

**Comment by kdionne-cglp** [comment]
Same problem here :
ERROR :
 There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

**Comment by tomobak** [comment]
Mine was just recovered.  Thank you for the fix!
Would you let us know what is the cause & fix and this issue would be happening often in the future?
Thank you again for your fix!

**Comment by OlivierCC** [comment]
CDN was down, webparts are now available
