### ISSUE TITLE
Markdown stopped working in IE, Firefox

### ISSUE THREAD

**Issue by cconry1** [OlivierCC/spfx-40-fantastics#108]
As of 9/24/2019 the Markdown app stopped working in our O365 tenant.  We have invested a large amount of time into this application and have a large user base.  Any resolution would be greatly appriciated. 

The error details are below

**Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
[SPLoaderError.loadComponentError]:
***Failed to load component "1431c215-2c2a-479c-a483-51b474c7bc88" (Markdown). Original error: ***Failed to load URL 'https://spfx40fantastics.azureedge.net/spfx40fantastics/showdown_b94bc96e28da2032a19583819bff8da6.js' for resource 'showdown' in component '1431c215-2c2a-479c-a483-51b474c7bc88' (Markdown). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

***INNERERROR:
***Failed to load URL 'https://spfx40fantastics.azureedge.net/spfx40fantastics/showdown_b94bc96e28da2032a19583819bff8da6.js' for resource 'showdown' in component '1431c215-2c2a-479c-a483-51b474c7bc88' (Markdown). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.
***CALLSTACK:
t@https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-09-13.009/sp-pages-assembly_en-us_ec9244e0470ebea1d6ad4db7f56d00c0.js:4:53495
t@https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-09-13.009/sp-pages-assembly_en-us_ec9244e0470ebea1d6ad4db7f56d00c0.js:20:48986
jx2P/s</e.buildErrorWithVerboseLog@https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-09-13.009/sp-pages-assembly_en-us_ec9244e0470ebea1d6ad4db7f56d00c0.js:20:112759
jx2P/s</e.buildLoadComponentError@https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-09-13.009/sp-pages-assembly_en-us_ec9244e0470ebea1d6ad4db7f56d00c0.js:20:108790
e/</<@https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-09-13.009/sp-pages-assembly_en-us_ec9244e0470ebea1d6ad4db7f56d00c0.js:20:45200**

**Comment by bholapaki** [comment]
Same issue here

**Comment by forrman** [comment]
We're seeing the same HTTPS cert error too.

**Comment by CRTSEMINOLE** [comment]
Same here as well. I really hope this can be fixed soon

**Comment by cconry1** [comment]
Does anyone know if this is being supported still?   We want to know if our organization needs to look for an alternative solution.

**Comment by OlivierCC** [comment]
CDN was down, webparts are now available

**Comment by cconry1** [comment]
Thank you @OlivierCC very much appreciate your quick support.
