### ISSUE TITLE
https://spfx40fantastics.azureedge.net/spfx40fantastics down - do you have a copy of the JS file?

### ISSUE THREAD

**Issue by SharePointPro** [OlivierCC/spfx-40-fantastics#109]
A hardcoded JS file used in the SPFX 40 fantastic webparts is not responding...

Is there any plans on fixing this? If there isn't does anyone have a copy of JS file so users update the code and host it themselves?

In particular: https://spfx40fantastics.azureedge.net/spfx40fantastics/spfx-40-fantastics-messagebarstrings_en-us_b00aa04f1d4b4bd642b19a24c2676fd3.js

**Comment by imdebourg** [comment]
Experiencing the same issue! It looks like the CDN tenant spfx40fantastics.azureedge.net is no more...

**Comment by kirti-prajapati** [comment]
Experiencing the same issue for all SPFx40 Web Parts installed in my development environment.

**Error as below for one of the Web Part:**

[SPLoaderError.loadComponentError]:
***Failed to load component "f6adeeb5-6e0c-46e8-a2e3-88b193b6c424" (NewsSlider). Original error: ***Failed to load URL **'https://spfx40fantastics.azureedge.net/spfx40fantastics/spfx-40-fantastics-sp-client-custom-fields_strings_en-us_517cbd7b26367d7a6cbe94ede5a0f7b8.js**' for resource 'sp-client-custom-fields/strings' in component 'f6adeeb5-6e0c-46e8-a2e3-88b193b6c424' (NewsSlider). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

***INNERERROR:
***Failed to load URL 'https://spfx40fantastics.azureedge.net/spfx40fantastics/spfx-40-fantastics-sp-client-custom-fields_strings_en-us_517cbd7b26367d7a6cbe94ede5a0f7b8.js' for resource 'sp-client-custom-fields/strings' in component 'f6adeeb5-6e0c-46e8-a2e3-88b193b6c424' (NewsSlider). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.
***CALLSTACK:
Error
   at t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-09-13.009/sp-pages-assembly_en-us_ec9244e0470ebea1d6ad4db7f56d00c0.js:4:53343)
   at t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-09-13.009/sp-pages-assembly_en-us_ec9244e0470ebea1d6ad4db7f56d00c0.js:20:48978)
   at e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-09-13.009/sp-pages-assembly_en-us_ec9244e0470ebea1d6ad4db7f56d00c0.js:20:112753)
   at e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-09-13.009/sp-pages-assembly_en-us_ec9244e0470ebea1d6ad4db7f56d00c0.js:20:108778)
   at Anonymous function (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-09-13.009/sp-pages-assembly_en-us_ec9244e0470ebea1d6ad4db7f56d00c0.js:20:45190)


@OlivierCC  - Can you please help on this as it seems the link for CDN tenant is not working.

**Comment by yazzouu** [comment]
Please, we have the same issue on all my sharepoint sites... Any ideas ?

**Comment by nav67** [comment]
Yes we started having the same issue since yesterday morning. Can anyone let us know for an ETA or suggest they are already working on it. Thank you

**Comment by yazzouu** [comment]
For all you, I removed the package from my app catalog and re-installed it and now it's working.

**Comment by OlivierCC** [comment]
This issue is fixed since 3 hours. The CDN was down and is now available.
