### ISSUE TITLE
WebParts not working

### ISSUE THREAD

**Issue by JakeDuq** [OlivierCC/spfx-40-fantastics#110]
SPLoaderError.loadComponentError]:
***Failed to load component "89d609dd-9fb6-4353-aab4-6215ac1bb7f6" (Accordion). Original error: ***Failed to load URL 'https://spfx40fantastics.azureedge.net/spfx40fantastics/jqueryui_caedcd0d9b40346f7533890cb04acbbd.js' for resource 'jqueryui' in component '89d609dd-9fb6-4353-aab4-6215ac1bb7f6' (Accordion). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

***INNERERROR:
***Failed to load URL 'https://spfx40fantastics.azureedge.net/spfx40fantastics/jqueryui_caedcd0d9b40346f7533890cb04acbbd.js' for resource 'jqueryui' in component '89d609dd-9fb6-4353-aab4-6215ac1bb7f6' (Accordion). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.
***CALLSTACK:
Error
    at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-09-13.009/sp-pages-assembly_en-us_ec9244e0470ebea1d6ad4db7f56d00c0.js:4:53495)
    at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-09-13.009/sp-pages-assembly_en-us_ec9244e0470ebea1d6ad4db7f56d00c0.js:20:48986)
    at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-09-13.009/sp-pages-assembly_en-us_ec9244e0470ebea1d6ad4db7f56d00c0.js:20:112759)
    at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-09-13.009/sp-pages-assembly_en-us_ec9244e0470ebea1d6ad4db7f56d00c0.js:20:108790)
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-09-13.009/sp-pages-assembly_en-us_ec9244e0470ebea1d6ad4db7f56d00c0.js:20:45200

Saw this error was going around a couple of days ago and then saw it was supposedly fixed. However I am still getting this error for all of the web parts, I have tried adding them to a different tenant, removing the web parts and adding them again however I still get this error. 

Is anyone experiencing this issue? And the people who managed to fix it did you have to do anything or just wait?

Cheers

**Comment by aaronbell29** [comment]
Yes, all the apps have stopped working for us.Hopefully @OlivierCC is working on it.

**Comment by yazzouu** [comment]
@OlivierCC  : I think The CDN is down again :)

**Comment by aaronbell29** [comment]
thanks, do you know when it will be back up?

**Comment by hrn111** [comment]
Same!!

**Comment by bholapaki** [comment]
Was fixed Yesterday but issue has returned this morning.

**Comment by tomobak** [comment]
Same here!

**Comment by tahamidur** [comment]
Same here..I hope @OlivierCC looking into the issue...

**Comment by aaronmi** [comment]
Trying to contact @OlivierCC and asking him to make the deployed files available for download. So everyone can host the solution in their tenant to avoid the issue again.

**Comment by neivas** [comment]
Do you have any idea when it will come back to work properly? Thanks, Neiva

**Comment by aaronmi** [comment]
Thanks to @OlivierCC. It should back online now.

**Comment by tahamidur6232** [comment]
working again...Yay...Thank you @OlivierCC  @aaronmi
