### ISSUE TITLE
Facing issue while adding NewsTicker to sharepoint page

### ISSUE THREAD

**Issue by divyavaniponugotu** [OlivierCC/spfx-40-fantastics#12]
Hi @OlivierCC ,

I am facing below issue while adding packaged NewsTicker webpart to my sharepoint page. The same is working in sharepoint workbench.

![image](https://cloud.githubusercontent.com/assets/24792883/24953457/fc49db38-1f98-11e7-841e-5abe60031155.png)

Please suggest how to solve this.

**Comment by natelabo** [comment]
The CDN appears to be down...

spfx-40-fantastics.azureedge.net or something like that...

I had to upload the assets on our own environment to make this work.

**Comment by RishanM** [comment]
I had the same error with the accordion. This resolved it for me: https://github.com/SharePoint/sp-dev-docs/issues/545

**Comment by OlivierCC** [comment]
Thanks for this tip @RishanM, I will fix it for the next version. 

@natelabo The CDN seems to work now. Let me know if you have an issue with the CDN again.

**Comment by divyavaniponugotu** [comment]
Thanks  @RishanM , SharePoint/sp-dev-docs/issues/545 fixed mine.
