### ISSUE TITLE
Multiple Instances

### ISSUE THREAD

**Issue by natelabo** [OlivierCC/spfx-40-fantastics#13]
I am trying to add different web parts to the same page. When I add these only a single instance of the web part appears to work. Is there a way to make a news tiles and news carousel work on the same page?

**Comment by OlivierCC** [comment]
Hi @natelabo, do you use the released package available in the releases page (https://github.com/OlivierCC/spfx-40-fantastics/releases) or your own copy ? I had a similar issue in the past, but normally the 1.0.2 version distributed in this page has a durty fix for that (fix with a custom version of jQuery for the moment).

**Comment by natelabo** [comment]
I setup a new dev environment. I'm sure I'm probably pulling from the jQuery repository. I'll attempt to revert to the version that is included with this package.

**Comment by OlivierCC** [comment]
The problem with the new tiles & news carousel come from unitegallery and the SharePoint Framework : 
1: unitegallery is better with jquery version < 3.X
2: with the SharePoint Framework, each version try to load jQuery. jQuery is loaded only 1 time of course, but the fact to call it again will erase the previous jQuery plugins. So in the 40 Fantastic CDN, the jQuery version contains a fix to be sure that if jQuery is already loaded, the jQuery plugins will not be erased.

I will try to find a better fix in the future.

Regards,

Olivier

**Comment by natelabo** [comment]
Thank you for your response... I'm pretty new to this can you point me to where I can find your jQuery version and how do I reference it. I'm looking through the commits for 1.0.2 but I'm not seeing where it was changed.

Also I've created another issue regarding using the new sp-client-custom-fields.

**Comment by OlivierCC** [comment]
sure, the jQuery version with the fix is available from the CDN here: http://spfx40fantastics.azureedge.net/spfx40fantastics/jquery_510295b52d8a7cc774bf4fb013893d1e.js

**Comment by natelabo** [comment]
Worked like a charm. Thanks!
