### ISSUE TITLE
There is an error in the config file:

### ISSUE THREAD

**Issue by mcrego003** [OlivierCC/spfx-40-fantastics#2]
Hello,

The line 274 says: 
"SyntaxHighlighterStrings": "webparts/code/loc/{locale}.js",

But it should be:
"SyntaxHighlighterStrings": "webparts/qrCode/loc/{locale}.js",

Great webparts!

Regards

**Comment by JonasBjerke89** [comment]
See issue #3 instead. It should be changed from code to syntaxHighlighter - not qrCode.

**Comment by OlivierCC** [comment]
Thaks a lot for this report. The bug is fixed and will be push in the next commit.
