### ISSUE TITLE
Tabs Web Part Not Fully Functional in Modern Page

### ISSUE THREAD

**Issue by hrn111** [OlivierCC/spfx-40-fantastics#22]
After adding the Tabs wp to my modern page, I noticed that I do not see the toolbars as pictured in your Overview, and I can only update the first tab.  Clicking additional tabs kicks the wp out of edit mode.  

Same results in Chrome version 58.0.3029.110 (64-bit), Internet Explorer 11 version 11.672.105860.0, and Edge 25.10586.672.0 (HTML 13.10586)

To better illustrate, see this [video snip](https://flic.kr/p/Ut79sw).   Any words of wisdom?

**Comment by OlivierCC** [comment]
Thanks you @hrn111 for this bug report. We will correct it soon.
Regards,
Olivier

**Comment by OlivierCC** [comment]
Hi @hrn111, I confirm you that this bug is now fix in the new version 1.0.4.0, available in the source control or here:  https://github.com/OlivierCC/spfx-40-fantastics/releases

Thanks again for your bug report, regards,

Olivier
