### ISSUE TITLE
Markdown tables not being converted

### ISSUE THREAD

**Issue by guzzd** [OlivierCC/spfx-40-fantastics#23]
Tables doesn't get converted.
Is there any way to turn on and off these options for markdown/showdown?

**Comment by OlivierCC** [comment]
Hi @guzzd,

This web part uses showdown JS (https://github.com/showdownjs/) to render the markdown. I checked in the showdown documentation, and to support tables we need to add a specific option (see doc about tables here: https://github.com/showdownjs/showdown/wiki/Showdown's-Markdown-syntax).

Today, the web part does not use this option. I will add it the next release.

Thanks you for this bug report, regards,

Olivier

**Comment by OlivierCC** [comment]
Hi @guzzd,

I can confirm that the next version of the package will contain the fix. If you are using the prepackaged file, I will pushing it very soon. If you are using the code version directly, you can get the fix here (line 116): https://github.com/OlivierCC/spfx-40-fantastics/blob/master/src/webparts/markdown/MarkdownWebPart.ts
 
Olivier

**Comment by guzzd** [comment]
Excellent, thanks for that!
