### ISSUE TITLE
Regarding issue #2

### ISSUE THREAD

**Issue by JonasBjerke89** [OlivierCC/spfx-40-fantastics#3]
Config.json - localizedResources:
It should be changed from "code" to "syntaxHighlighter" - not qrcode, as mentioned in issue #2:
![image](https://cloud.githubusercontent.com/assets/21952399/20207433/75c8b9b8-a7e7-11e6-84ff-e8dde593a820.png)
![image](https://cloud.githubusercontent.com/assets/21952399/20207438/7a0c898c-a7e7-11e6-8532-8db302d6ced6.png)

**Comment by OlivierCC** [comment]
Thanks a lot, fix in the next commit
