### ISSUE TITLE
***Failed to load component "ee6ccc68-d0ec-456c-8968-08a705191cf1"

### ISSUE THREAD

**Issue by warwickbuilds** [OlivierCC/spfx-40-fantastics#34]
Anyone else seeing this in their Tenant, none of the 40 webparts are loading due to not being able to load the js file. Browsing to the JS file url opens it fine.

Any Ideas?

[SPLoaderError.loadComponentError]:
***Failed to load component "ee6ccc68-d0ec-456c-8968-08a705191cf1" (TilesMenu).
Original error: ***Failed to load URL 'https://spfx40fantastics.azureedge.net/spfx40fantastics/unitegallery_7d9eb985d2d3c164e19835ea4e33161e.js' for resource 'unitegallery' in component 'ee6ccc68-d0ec-456c-8968-08a705191cf1' (TilesMenu). There was a network problem.
This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

***INNERERROR:
***Failed to load URL 'https://spfx40fantastics.azureedge.net/spfx40fantastics/unitegallery_7d9eb985d2d3c164e19835ea4e33161e.js' for resource 'unitegallery' in component 'ee6ccc68-d0ec-456c-8968-08a705191cf1' (TilesMenu). There was a network problem.
This may be a problem with a HTTPS certificate. Make sure you have the right certificate.
***CALLSTACK:
Error
    at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-07.013/sp-pages-assembly_en-us_2c73e80d5a13bd005205d9613ee5cdc2.js:351:10483)
    at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-07.013/sp-pages-assembly_en-us_2c73e80d5a13bd005205d9613ee5cdc2.js:911:17735)
    at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-07.013/sp-pages-assembly_en-us_2c73e80d5a13bd005205d9613ee5cdc2.js:911:14892)
    at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-07.013/sp-pages-assembly_en-us_2c73e80d5a13bd005205d9613ee5cdc2.js:911:12701)
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-07.013/sp-pages-assembly_en-us_2c73e80d5a13bd005205d9613ee5cdc2.js:911:104583
    at <anonymous>

**Comment by screwfacekilla** [comment]
We are experiencing this as well. 

If the problem persists, contact the site administrator and give them the information in Technical Details.
Technical Details
***ERROR MESSAGE: ***Failed to load component "ee6ccc68-d0ec-456c-8968-08a705191cf1" (TilesMenu). Original error: ***Failed to load URL 'https://spfx40fantastics.azureedge.net/spfx40fantastics/tilesmenu.bundle_d1f5d36cfae1b9d701da525c10b7c3e0.js' for resource 'tilesMenu.bundle' in component 'ee6ccc68-d0ec-456c-8968-08a705191cf1' (TilesMenu). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate. ***CALLSTACK: Error at t._generateErrorStackForIE (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-14.008/sp-classic-page-assembly_en-us_018b2ed736560244bcaa233c9aea8b22.js:206:10795) at t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-14.008/sp-classic-page-assembly_en-us_018b2ed736560244bcaa233c9aea8b22.js:206:10315) at t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-14.008/sp-classic-page-assembly_en-us_018b2ed736560244bcaa233c9aea8b22.js:501:16696) at e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-14.008/sp-classic-page-assembly_en-us_018b2ed736560244bcaa233c9aea8b22.js:501:13911) at e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-14.008/sp-classic-page-assembly_en-us_018b2ed736560244bcaa233c9aea8b22.js:501:11714) at Anonymous function (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-14.008/sp-classic-page-assembly_en-us_018b2ed736560244bcaa233c9aea8b22.js:501:104302) at q (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-14.008/sp-classic-page-assembly_en-us_018b2ed736560244bcaa233c9aea8b22.js:8:2379) at B (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-14.008/sp-classic-page-assembly_en-us_018b2ed736560244bcaa233c9aea8b22.js:8:2467) at k (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-14.008/sp-classic-page-assembly_en-us_018b2ed736560244bcaa233c9aea8b22.js:8:2289) at L (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-14.008/sp-classic-page-assembly_en-us_018b2ed736560244bcaa233c9aea8b22.js:8:1885)

**Comment by warwickbuilds** [comment]
Looks to be fixed now, not sure what happened, looks to be lots of bugs happening with the Modern pages and sites Microsoft is rolling out
