### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by allakib** [OlivierCC/spfx-40-fantastics#4]
Hi Oliver,
Great stuff to learn Sharepoint Framework
We installed as you recommended
git clone the repo
npm i
npm i -g gulp
gulp serve

It works in the local environment. However we run workbench hosted in Sharepoint we have the error "Cannot read property 'bind' of undefined"

Could you advise?
Thank you

**Comment by OlivierCC** [comment]
Hi, thanks for this report. Can you tell me with which web part this error occurs please ? Thx, Olivier

**Comment by allakib** [comment]
Hi Oliver,
Thanks a lot for your reply.
I attach what we have when adding 3DCarousel on a page

Thanks
Alla

**Comment by allakib** [comment]
Here is the attached pic
[cid:image001.jpg@01D24FB2.13553550]

**Comment by allakib** [comment]
![spfx40fantastics](https://cloud.githubusercontent.com/assets/24276338/20933496/3ddf18ee-bba6-11e6-9c9d-b360fc12235b.gif)

**Comment by nigelzin** [comment]
Hi,

I don't know if you see the error, but we have message like "Error loading https://placeholder-base-url (...)" at second line.

**Comment by OlivierCC** [comment]
Hi,
Can you try with the latest version please (version 0.9.1 published this week) ? May be a problem of SPFx version (the release of this week) is ready for the current SPFx version (Drop 6).
Be sure to update also your dev env with this version.
Thanks,
Olivier

**Comment by allakib** [comment]
Thank you. When I updated yeoman, npm, gulp, sharepoint generator and loaded again spfx-40-fantastics it is much better now. Works but not perfect, e.g. 3DCarousel  shows the empty carousel and on editing shows "No settings to change for this web part."

Thanks for help to make it working. I will test carefully later.

**Comment by allakib** [comment]
Hi Olivier,
I updated SPFX-40-fantastics to RC0 version
It works fine under the workbench (local and dev site)
I load to Apps on Dev tenant, delete old one and added the new 40-fantastics on the page. It doesn't work. Please have a look at the errors and consult.

_[SPWebPartErrorCode.ScriptLoadError]:: Unable to load web part WebPart.ArcText.g_2d5c23c5_76d9_47c8_96e9_4c9a5b4ac5f3,Error: ***Failed to load component "6b1bd026-d733-4828-85ba-41fdae288a45" (ArcText). Original error: ***Failed to load path dependency "arcTextStrings" from component "6b1bd026-d733-4828-85ba-41fdae288a45" (ArcText). script resources due to: undefined. CALLSTACK:: Error at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-01-30.050/sp-loader_en-us_8dcc40dbed7d342cb798684ccc3d8e01.js:57:19057) at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-01-30.050/sp-webpart-base_en-us_82e08ac23ada35737a294061bfc71d60.js:47:22053) at Function.t.create (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-01-30.050/sp-webpart-base_en-us_82e08ac23ada35737a294061bfc71d60.js:47:22502) at https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-01-30.050/sp-webpart-base_en-us_82e08ac23ada35737a294061bfc71d60.js:48:714_


Greatly appreciate
The best 
Alla

**Comment by OlivierCC** [comment]
Hi @allakib and @nigelzin, the web parts are now available as a precompiled package. You can now easily try and test the web parts with the following process: https://github.com/OlivierCC/spfx-40-fantastics/wiki/Installation-process

Regards,

Olivier

**Comment by allakib** [comment]
Hi Olivier,
I updated 40 Fantastics yesterday. I was so upset I could see the webparts in Custom or Under Development categories and spent a few hours to understand why. Thanks for explanation  where it lives now. It works fine now when you refused from SPComponentLoader. Many thanks for these wonderful webparts. I hope you will present us more and more great development for SPFx.
