### ISSUE TITLE
Problem to install

### ISSUE THREAD

**Issue by tommrihu** [OlivierCC/spfx-40-fantastics#5]
Hi 
looks great but i dont really dont understand how to install it
could you push me  in right direction to install it in our Tenant

/Tommy

**Comment by OlivierCC** [comment]
Hi Tommy, for the moment SPFx is still in preview, so it's not available to install it in a production tenant. You can try these webparts only in a dev mode. Normally the SPFx will be release soon, so you will be able to deploy it as "classical" web parts in the future.
Regards,
Olivier

**Comment by tommrihu** [comment]
Thanks Olivier!

Med Vänliga Hälsningar/Best Regards
-------------------------------------------------------------------
Tommy Rihu
Office +46 (0)522 98027
Direct +46 (0)706 28 44 00
www.uanet.se<http://www.uanet.se/>
Gustaf Mattssons Väg 2
451 50 Uddevalla
Orgnr: 556702-4095
[http://www.uanet.se/emailsignature/logo-uanet-email.jpg]


Från: Olivier Carpentier [mailto:notifications@github.com]
Skickat: den 22 januari 2017 14:38
Till: OlivierCC/spfx-40-fantastics <spfx-40-fantastics@noreply.github.com>
Kopia: Tommy Rihu <tommy@uanet.se>; Author <author@noreply.github.com>
Ämne: Re: [OlivierCC/spfx-40-fantastics] Problem to install (#5)


Hi Tommy, for the moment SPFx is still in preview, so it's not available to install it in a production tenant. You can try these webparts only in a dev mode. Normally the SPFx will be release soon, so you will be able to deploy it as "classical" web parts in the future.
Regards,
Olivier

**Comment by OlivierCC** [comment]
Hi @tommrihu, the web parts are now available as a precompiled package. You can now easily try and test the web parts with the following process: https://github.com/OlivierCC/spfx-40-fantastics/wiki/Installation-process

Regards,

Olivier
