### ISSUE TITLE
FckText is not available in webpart list/gallery. 

### ISSUE THREAD

**Issue by kathiravank83** [OlivierCC/spfx-40-fantastics#63]
I have sucessfully installed fanstastic 40 and i can able to use some of the webparts. When i try to use the fckText but could not. Its not available in webpart list/gallery and also not available in site features. Any insights on this issue?

**Comment by spidersbite** [comment]
I'm looking for this webpart as well. Does anyone look at these issues? 
I was tempted to reinstall the app to see if there were updates but am hesitant since no one seems to be troubleshooting.

**Comment by AltruisticNerd** [comment]
It's titled  RichText Editor in the Web parts selector, not fckText.

**Comment by kathiravank83** [comment]
Thanks, But when i tried to load the RichTextEditor webpart but does not shows up the editor control. I am not able to use it at all

**Comment by AltruisticNerd** [comment]
Yes.  Microsoft broke this part.  See #29

**Comment by kathiravank83** [comment]
Thanks!
