### ISSUE TITLE
Valid App Package = No

### ISSUE THREAD

**Issue by robhasos** [OlivierCC/spfx-40-fantastics#7]
Hi, 

I've tried to install the sppkg in the App Catalog but it doesn't seem to recognise the package. While there are no upload errors, "Valid App Package" is set to No, the product Id doesn't look right  and I can't add the app to any site. See the image below...

![image](https://cloud.githubusercontent.com/assets/11299507/23449898/4414ebb6-fe50-11e6-8d3b-8b06091d3a9d.png)

Any ideas what's wrong?

**Comment by OlivierCC** [comment]
Thanks @robhasos for your feedback. I can not reproduce it on my test tenants. The SharePoint Framework is currently in rolled out to all 0365 tenancies, may be your tenant is not yet ready. You can try to deploy it later (wait few days) and I will try to find your a simple process to check what is your tenant status.

**Comment by OlivierCC** [comment]
@robhasos, an "easy" way to check the version of the SPFx on your tenant can be:
1. Create a "modern site" (for example create a new O365 group with a SharePoint site attached)
2. Go to a page (home for example) and open your browser debugguer with the Network tab
3. Check the JS files loaded, and verify what is the URL of the JS files from the CDN: the good SPFx version shoud have a "2017-02-17" value in path (see the attached picture bellow).

![spfxv1check](https://cloud.githubusercontent.com/assets/16818544/23451164/1176b48c-fe5f-11e6-949c-2804f84d0936.png)

Thanks a lot by advance if you can test it and report to me if this is the explanation. Regards,
Olivier

**Comment by robhasos** [comment]
Hi Olivier,

Looks like it is enabled... 
`<link href="https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-02-17.019/sp-pages.bundle_en-us_29d9d18da3b22ea10154880027f99253.js" rel="preload" as="script">`

Should be as we are First Release tenant. 

I've contacted support to see whether SPFX has been properly rolled out to our tenant.

Thanks,

Rob

**Comment by OlivierCC** [comment]
Thanks a lot. I will continue to investigate, stay tuned.

**Comment by sprisock** [comment]
I'm having the exact same experience as @robhasos when trying to install to the app catalog.

**Comment by robhasos** [comment]
O365 Support have told me the rollout is still in progress.

**Comment by OlivierCC** [comment]
OK thanks for your answer @robhasos. Please tell me when your tenant will be ready if it's working or not.

**Comment by baskb** [comment]
Also my tenant has the 02-17 JS files, but can't install the package in my app catalogue

**Comment by sprisock** [comment]
yes, thanks @robhasos -- that response is so disappointing, but not at all surprising. I feel like they lean on that vague response way too much these days.

**Comment by Haasma** [comment]
Hi @OlivierCC 

Having the same issue here with app installation:
<img width="1111" alt="sss" src="https://cloud.githubusercontent.com/assets/22379096/23577165/d99c2720-00b8-11e7-8be5-1f3b763739dc.PNG">

Correct #SPFx version is loaded, but App has no ID, Product ID and says that app package is not valid. 

Thx for your help!

**Comment by Haasma** [comment]
https://github.com/SharePoint/sp-dev-docs/issues/276 as discussed here also, I think the issue is that, we are somehow stil not completely rolled out when it comes to #SPFx. References in pages are there, but it looks like smth is missing. We have first release activated only for several users? Should it be activated for all maybe? Whats your setting there? As it's GA now, I don't see the need to set first release for this matter. Or am I wrong here?

**Comment by Haasma** [comment]
tested on different o365 tenants now and I get the same behavior if all users in first release, or just some.

**Comment by Haasma** [comment]
After turning on First Release for all Users, I was able to deploy and activate the Webparts. Thank you!

**Comment by mistergee2010** [comment]
Hi, 
Completely new to Office 365. But really hope to use the coverflow web part for my school community. I am experiencing what all others are stating here. I however don't fully understand what the fix is. Can someone break it down into basic step by step for us NOOBs out there?
Thanks

**Comment by OlivierCC** [comment]
Hi @mistergee2010, there is no specific fix: you need to wait that the new SharePoint Framewok rollout is completed. A possibility to go faster is to use the functionality called 'First release' for all your users. This means that your tenant receives updates before the normal date. You can read more information about how to configure it here: https://support.office.com/en-us/article/Set-up-the-Standard-or-First-Release-options-in-Office-365-3b3adfa4-1777-4ff0-b606-fb8732101f47?ui=en-US&rs=en-US&ad=US

**Comment by mistergee2010** [comment]
?Thanks for replying we will have a look at it

________________________________

**Comment by baskb** [comment]
Waiting until my tenant was ready fixed the issue. Things started working for me yesterday.

Love the modern webparts!!! Thanks

**Comment by robhasos** [comment]
If better try again now!

________________________________

**Comment by robhasos** [comment]
Whoop! Works for me too now.

@OlivierCC , thanks for your great work on these webparts.
